apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zy0e
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-zy0e@sha256:8aeb16245ee128ab31982cbd7842686b91913915f9df36d13617844dc97cd225
        name: my-nodejs
        resources: {}
status: {}
